### ISSUE TITLE
Create a proper setup script

### ISSUE THREAD

**Issue by rodluger** [VirtualPlanetaryLaboratory/vspace#1]
The setup script for `vspace` should use `setuptools`, as in

https://github.com/VirtualPlanetaryLaboratory/bigplanet/blob/master/setup.py

The current setup script doesn't allow `vspace` to be listed as a dependency of `vplanet` since `setuptools` doesn't recognize it as a valid Python package.

**Comment by caitlyn-wilhelm** [comment]
Should be fixed now on the master branch!
